---
# SPANK module install path on Debian/Ubuntu
# Package install: /usr/lib/x86_64-linux-gnu/slurm
# Source install: {{ slurm_install_prefix }}/lib/slurm
# Default assumes Slurm is installed from source
pyxis_spank_module_path: "{{ slurm_install_prefix | default('/usr/local') }}/lib/slurm"
pyxis_slurmd_service_name: "slurmd"
pyxis_slurmctld_service_name: "slurmctld"
