---
# Docker role defaults

docker_version: "28"
containerd_version: "1.7.27"
docker_enabled: false
docker_storage_driver: "overlay2"
docker_log_driver: "json-file"
docker_force_reinstall: false
docker_repository_url:
  RedHat: "https://download.docker.com/linux/rhel/{{ ansible_facts['distribution_major_version'] }}/{{ ansible_facts['architecture'] }}/stable"
  Debian: "https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/stable"
