---
# NFS Server Handlers

- name: restart nfs server
  ansible.builtin.systemd:
    name: "{{ 'nfs-server' if ansible_facts['os_family'] == 'RedHat' else 'nfs-kernel-server' }}"
    state: restarted
    daemon_reload: true
